
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblCod = new javax.swing.JLabel();
        LblProduto = new javax.swing.JLabel();
        LblQuantidade = new javax.swing.JLabel();
        LblPrecodeCompra = new javax.swing.JLabel();
        LblPrecodeVenda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JtfCod = new javax.swing.JTextField();
        JtfProduto = new javax.swing.JTextField();
        JtfQuantidade = new javax.swing.JTextField();
        JtfPrecodeCompra = new javax.swing.JTextField();
        JtfPrecodeVenda = new javax.swing.JTextField();
        JtfMargemdeVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtgSalvar = new javax.swing.JButton();
        BtgExcluir = new javax.swing.JButton();
        BtgNovo = new javax.swing.JButton();
        BtgSair = new javax.swing.JButton();
        BtgCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCod.setText("Cod:");

        LblProduto.setText("Produto:");

        LblQuantidade.setText("Quantidade:");

        LblPrecodeCompra.setText("Preço de Compra:");

        LblPrecodeVenda.setText("Preço de Venda:");

        jLabel1.setText("Margem de Venda:");

        JtfCod.setText(" ");
        JtfCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfCodActionPerformed(evt);
            }
        });

        JtfProduto.setText(" ");
        JtfProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfProdutoActionPerformed(evt);
            }
        });

        JtfQuantidade.setText("    ");
        JtfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfQuantidadeActionPerformed(evt);
            }
        });

        JtfPrecodeCompra.setText(" ");

        JtfPrecodeVenda.setText(" ");

        JtfMargemdeVenda.setText(" ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "Quantidade", "Compra", "Venda", "Margem"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtgSalvar.setText("Salvar");
        BtgSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgSalvarActionPerformed(evt);
            }
        });

        BtgExcluir.setText("Excluir");
        BtgExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgExcluirActionPerformed(evt);
            }
        });

        BtgNovo.setText("Novo");
        BtgNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgNovoActionPerformed(evt);
            }
        });

        BtgSair.setText("Sair");
        BtgSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgSairActionPerformed(evt);
            }
        });

        BtgCancelar.setText("Cancelar");
        BtgCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblCod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtgExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtgNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227)
                                .addComponent(BtgSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LblPrecodeCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(LblPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfMargemdeVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtgSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(BtgCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCod)
                    .addComponent(LblProduto)
                    .addComponent(LblQuantidade)
                    .addComponent(JtfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrecodeCompra)
                    .addComponent(LblPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JtfPrecodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfPrecodeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfMargemdeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtgSalvar)
                    .addComponent(BtgCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtgExcluir)
                    .addComponent(BtgNovo)
                    .addComponent(BtgSair))
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfProdutoActionPerformed

    private void JtfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfQuantidadeActionPerformed

    private void JtfCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfCodActionPerformed

    private void BtgSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgSalvarActionPerformed
        
//Não funcionou, tentei!
           DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        
            String linha[] = new String[6];

            linha[0] = JtfCod.getText();
            linha[1] = JtfProduto.getText();
            linha[2] = JtfQuantidade.getText();
            linha[3] = JtfPrecodeCompra.getText();
            linha[4] = JtfPrecodeVenda.getText();

            double venda = Double.parseDouble(JtfPrecodeVenda.getText());
            double compra = Double.parseDouble(JtfPrecodeCompra.getText());
            double margem = ((venda - compra) / compra) * 100;

            linha[5] = Double.toString(margem);

            modelo.addRow(linha);
            JtfCod.setText("");
            JtfProduto.setText("");
            JtfQuantidade.setText("");
            JtfPrecodeCompra.setText("");
            JtfPrecodeVenda.setText("");
            JtfMargemdeVenda.setText("");
            JtfCod.requestFocus();
    }//GEN-LAST:event_BtgSalvarActionPerformed

    private void BtgExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgExcluirActionPerformed
//Não consegui cadastrar, logo não sei se funciona.
        DefaultTableModel Modelo = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRow() >= 0)
        {
            int response = JOptionPane.showConfirmDialog(null, "Deseja excluir dado?", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
            if(response == JOptionPane.YES_OPTION)
            {
                //Modelo.removeRow(jTable1.getSelectedRow());
               //jTable1.setModel(Modelo);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor selecione a Linha que deseja excluir");
        }
    }//GEN-LAST:event_BtgExcluirActionPerformed

        
    private void BtgCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgCancelarActionPerformed
      //Funcionou,Eba!
        int response =JOptionPane.showConfirmDialog(null,"Deseja Cancelar?","Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        JtfCod.setText("");
        JtfProduto.setText("");
        JtfQuantidade.setText("");
        JtfPrecodeCompra.setText("");
        JtfPrecodeVenda.setText("");
        JtfMargemdeVenda.setText("");
        }
    }//GEN-LAST:event_BtgCancelarActionPerformed

    private void BtgSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgSairActionPerformed
        //Funcionou,Eba!    
       int response = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmação", 
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
       if(response == JOptionPane.YES_OPTION)
       {
           System.exit(0);
       }



        
        
    }//GEN-LAST:event_BtgSairActionPerformed

    private void BtgNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgNovoActionPerformed
     //Funcionou,Eba!
        int response =JOptionPane.showConfirmDialog(null,"Deseja Cadastrar um Novo Produto?","Confirmação",
             JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
        JtfCod.setText("");
        JtfProduto.setText("");
        JtfQuantidade.setText("");
        JtfPrecodeCompra.setText("");
        JtfPrecodeVenda.setText("");
        JtfMargemdeVenda.setText("");
        }
    }//GEN-LAST:event_BtgNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtgCancelar;
    private javax.swing.JButton BtgExcluir;
    private javax.swing.JButton BtgNovo;
    private javax.swing.JButton BtgSair;
    private javax.swing.JButton BtgSalvar;
    private javax.swing.JTextField JtfCod;
    private javax.swing.JTextField JtfMargemdeVenda;
    private javax.swing.JTextField JtfPrecodeCompra;
    private javax.swing.JTextField JtfPrecodeVenda;
    private javax.swing.JTextField JtfProduto;
    private javax.swing.JTextField JtfQuantidade;
    private javax.swing.JLabel LblCod;
    private javax.swing.JLabel LblPrecodeCompra;
    private javax.swing.JLabel LblPrecodeVenda;
    private javax.swing.JLabel LblProduto;
    private javax.swing.JLabel LblQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
