/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtgOperacao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LblNumero1 = new javax.swing.JLabel();
        LblNumero2 = new javax.swing.JLabel();
        JtfNumero1 = new javax.swing.JTextField();
        JtfNumero2 = new javax.swing.JTextField();
        BtnFechar = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        LblResultado = new javax.swing.JLabel();
        LblValor = new javax.swing.JLabel();
        RdbSoma = new javax.swing.JRadioButton();
        RdbSubtrai = new javax.swing.JRadioButton();
        RdbMultiplica = new javax.swing.JRadioButton();
        RdbDivide = new javax.swing.JRadioButton();
        LblOperacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblNumero1.setText("Numero 1");

        LblNumero2.setText("Numero 2");

        JtfNumero1.setText("   ");
        JtfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNumero1ActionPerformed(evt);
            }
        });

        JtfNumero2.setText(" ");

        BtnFechar.setText("Fechar");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        BtnCalcular.setText("Calcular");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        LblResultado.setText("Resultado");

        LblValor.setText("0");

        BtgOperacao.add(RdbSoma);
        RdbSoma.setText("+");
        RdbSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbSomaActionPerformed(evt);
            }
        });

        BtgOperacao.add(RdbSubtrai);
        RdbSubtrai.setText("-");

        BtgOperacao.add(RdbMultiplica);
        RdbMultiplica.setText("*");

        BtgOperacao.add(RdbDivide);
        RdbDivide.setText("/");

        LblOperacao.setText("Operação:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LblNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(LblNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblResultado)
                                    .addComponent(LblOperacao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(RdbSoma)
                                        .addGap(18, 18, 18)
                                        .addComponent(RdbSubtrai)
                                        .addGap(18, 18, 18)
                                        .addComponent(RdbMultiplica)
                                        .addGap(18, 18, 18)
                                        .addComponent(RdbDivide))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(BtnCalcular)
                                .addGap(41, 41, 41)
                                .addComponent(BtnLimpar)))
                        .addGap(23, 23, 23)
                        .addComponent(BtnFechar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNumero1)
                    .addComponent(JtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblNumero2)
                    .addComponent(JtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblResultado)
                    .addComponent(LblValor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbSoma)
                    .addComponent(RdbSubtrai)
                    .addComponent(RdbMultiplica)
                    .addComponent(RdbDivide)
                    .addComponent(LblOperacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcular)
                    .addComponent(BtnLimpar)
                    .addComponent(BtnFechar))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNumero1ActionPerformed

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        // TODO add your handling code here:
        JtfNumero1.setText(" ");
        JtfNumero2.setText(" ");
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        // TODO add your handling code here:
        float Numero1;
        float Numero2;
        float Valor=0;
        
       //Sempre tem que ser convertido para String usando tipovariavel.valueOf(nomevarial.getText()); 
        Numero1 = Float.valueOf(JtfNumero1.getText());
        Numero2 = Float.valueOf(JtfNumero2.getText());
       
        if (RdbSoma.isSelected()){
         Valor= Numero1+Numero2;
        }
        if (RdbSubtrai.isSelected()){
         Valor= Numero1-Numero2;
        }
        if (RdbMultiplica.isSelected()){
         Valor= Numero1*Numero2;
        }  
        if (RdbDivide.isSelected()){
         Valor= Numero1/Numero2;
        }  
        
        
        //Convertendo o numero do valor pois era Float
       LblValor.setText(String.valueOf(Valor));
        
       
       
       
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void RdbSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbSomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgOperacao;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JTextField JtfNumero1;
    private javax.swing.JTextField JtfNumero2;
    private javax.swing.JLabel LblNumero1;
    private javax.swing.JLabel LblNumero2;
    private javax.swing.JLabel LblOperacao;
    private javax.swing.JLabel LblResultado;
    private javax.swing.JLabel LblValor;
    private javax.swing.JRadioButton RdbDivide;
    private javax.swing.JRadioButton RdbMultiplica;
    private javax.swing.JRadioButton RdbSoma;
    private javax.swing.JRadioButton RdbSubtrai;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
